<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PaketPengadaanSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        // ─── PAKET PENGADAAN ───────────────────────────────────────────────
        $pakets = [
            // ── 2024 (TA 1, programs 1-2) ──────────────────────────────────
            [
                'kode_paket' => 'PKT.2024.001',
                'nama_paket' => 'Pengadaan Laptop dan Notebook ASN',
                'uraian_pekerjaan' => 'Pengadaan sebanyak 100 unit laptop dan notebook untuk kebutuhan operasional ASN di lingkungan sekretariat',
                'pagu_anggaran' => 500_000_000,
                'hps' => 495_000_000,
                'status' => 'dipublikasikan',
                'unit_kerja_id' => 1,
                'tahun_anggaran_id' => 1,
                'program_id' => 1,
                'kegiatan_id' => 1,
                'sub_kegiatan_id' => 1,
                'sumber_dana_id' => 1,
                'jenis_pengadaan_id' => 1,
                'metode_pengadaan_id' => 1,
                'kategori_id' => 1,
                'satuan_id' => 1,
                'penyedia_id' => 1,
                'user_id' => 3,
                'is_published' => true,
                'published_at' => '2024-03-01 09:00:00',
            ],
            [
                'kode_paket' => 'PKT.2024.002',
                'nama_paket' => 'Pengadaan Printer dan Scanner',
                'uraian_pekerjaan' => 'Pengadaan printer multifungsi dan scanner dokumen untuk kebutuhan administrasi perkantoran',
                'pagu_anggaran' => 200_000_000,
                'hps' => 198_000_000,
                'status' => 'dipublikasikan',
                'unit_kerja_id' => 2,
                'tahun_anggaran_id' => 1,
                'program_id' => 1,
                'kegiatan_id' => 1,
                'sub_kegiatan_id' => 2,
                'sumber_dana_id' => 1,
                'jenis_pengadaan_id' => 1,
                'metode_pengadaan_id' => 4,
                'kategori_id' => 1,
                'satuan_id' => 1,
                'penyedia_id' => 4,
                'user_id' => 4,
                'is_published' => true,
                'published_at' => '2024-04-15 10:00:00',
            ],
            [
                'kode_paket' => 'PKT.2024.003',
                'nama_paket' => 'Renovasi Ruang Kerja Kantor',
                'uraian_pekerjaan' => 'Renovasi total ruang kerja kantor meliputi pengecatan, penggantian plafon, lantai, dan instalasi listrik',
                'pagu_anggaran' => 400_000_000,
                'hps' => 390_000_000,
                'status' => 'disetujui',
                'unit_kerja_id' => 1,
                'tahun_anggaran_id' => 1,
                'program_id' => 1,
                'kegiatan_id' => 2,
                'sub_kegiatan_id' => 3,
                'sumber_dana_id' => 1,
                'jenis_pengadaan_id' => 2,
                'metode_pengadaan_id' => 1,
                'kategori_id' => 7,
                'satuan_id' => 3,
                'penyedia_id' => 3,
                'user_id' => 3,
                'is_published' => false,
                'published_at' => null,
            ],
            [
                'kode_paket' => 'PKT.2024.004',
                'nama_paket' => 'Pembangunan Ruang Arsip Digital',
                'uraian_pekerjaan' => 'Pembangunan ruang khusus arsip digital dengan sistem penyimpanan, pengatur suhu, dan keamanan',
                'pagu_anggaran' => 350_000_000,
                'hps' => 345_000_000,
                'status' => 'dipublikasikan',
                'unit_kerja_id' => 2,
                'tahun_anggaran_id' => 1,
                'program_id' => 1,
                'kegiatan_id' => 2,
                'sub_kegiatan_id' => 4,
                'sumber_dana_id' => 1,
                'jenis_pengadaan_id' => 2,
                'metode_pengadaan_id' => 1,
                'kategori_id' => 7,
                'satuan_id' => 3,
                'penyedia_id' => 3,
                'user_id' => 4,
                'is_published' => true,
                'published_at' => '2024-05-20 09:00:00',
            ],
            [
                'kode_paket' => 'PKT.2024.005',
                'nama_paket' => 'Pengembangan Sistem Informasi Kepegawaian',
                'uraian_pekerjaan' => 'Pengembangan sistem informasi kepegawaian terintegrasi berbasis web meliputi modul data pegawai, absensi, cuti, dan kinerja',
                'pagu_anggaran' => 600_000_000,
                'hps' => 585_000_000,
                'status' => 'dipublikasikan',
                'unit_kerja_id' => 4,
                'tahun_anggaran_id' => 1,
                'program_id' => 2,
                'kegiatan_id' => 3,
                'sub_kegiatan_id' => 5,
                'sumber_dana_id' => 1,
                'jenis_pengadaan_id' => 3,
                'metode_pengadaan_id' => 5,
                'kategori_id' => 5,
                'satuan_id' => 3,
                'penyedia_id' => 5,
                'user_id' => 6,
                'is_published' => true,
                'published_at' => '2024-06-01 09:30:00',
            ],
            [
                'kode_paket' => 'PKT.2024.006',
                'nama_paket' => 'Pengembangan Aplikasi Layanan Publik',
                'uraian_pekerjaan' => 'Pengembangan aplikasi pelayanan publik terpadu berbasis mobile dan web untuk masyarakat',
                'pagu_anggaran' => 400_000_000,
                'hps' => 390_000_000,
                'status' => 'disetujui',
                'unit_kerja_id' => 8,
                'tahun_anggaran_id' => 1,
                'program_id' => 2,
                'kegiatan_id' => 3,
                'sub_kegiatan_id' => 6,
                'sumber_dana_id' => 1,
                'jenis_pengadaan_id' => 3,
                'metode_pengadaan_id' => 5,
                'kategori_id' => 5,
                'satuan_id' => 3,
                'penyedia_id' => 9,
                'user_id' => 10,
                'is_published' => false,
                'published_at' => null,
            ],
            [
                'kode_paket' => 'PKT.2024.007',
                'nama_paket' => 'Pengadaan Server dan Storage',
                'uraian_pekerjaan' => 'Pengadaan server blade dan storage area network untuk kebutuhan data center dan backup',
                'pagu_anggaran' => 500_000_000,
                'hps' => 495_000_000,
                'status' => 'dipublikasikan',
                'unit_kerja_id' => 5,
                'tahun_anggaran_id' => 1,
                'program_id' => 2,
                'kegiatan_id' => 4,
                'sub_kegiatan_id' => 7,
                'sumber_dana_id' => 1,
                'jenis_pengadaan_id' => 1,
                'metode_pengadaan_id' => 1,
                'kategori_id' => 1,
                'satuan_id' => 1,
                'penyedia_id' => 1,
                'user_id' => 7,
                'is_published' => true,
                'published_at' => '2024-07-10 08:00:00',
            ],
            [
                'kode_paket' => 'PKT.2024.008',
                'nama_paket' => 'Pengadaan Perangkat Jaringan',
                'uraian_pekerjaan' => 'Pengadaan switch, router, access point, dan kabel jaringan untuk infrastruktur kantor',
                'pagu_anggaran' => 250_000_000,
                'hps' => 247_500_000,
                'status' => 'dipublikasikan',
                'unit_kerja_id' => 5,
                'tahun_anggaran_id' => 1,
                'program_id' => 2,
                'kegiatan_id' => 4,
                'sub_kegiatan_id' => 8,
                'sumber_dana_id' => 1,
                'jenis_pengadaan_id' => 1,
                'metode_pengadaan_id' => 2,
                'kategori_id' => 1,
                'satuan_id' => 3,
                'penyedia_id' => 9,
                'user_id' => 7,
                'is_published' => true,
                'published_at' => '2024-07-15 10:00:00',
            ],
            [
                'kode_paket' => 'PKT.2024.009',
                'nama_paket' => 'Jasa Konsultansi Perencanaan Sistem Informasi',
                'uraian_pekerjaan' => 'Jasa konsultansi untuk perencanaan arsitektur sistem informasi dan roadmap transformasi digital',
                'pagu_anggaran' => 150_000_000,
                'hps' => 148_500_000,
                'status' => 'dipublikasikan',
                'unit_kerja_id' => 5,
                'tahun_anggaran_id' => 1,
                'program_id' => 2,
                'kegiatan_id' => 3,
                'sub_kegiatan_id' => 5,
                'sumber_dana_id' => 1,
                'jenis_pengadaan_id' => 3,
                'metode_pengadaan_id' => 6,
                'kategori_id' => 5,
                'satuan_id' => 3,
                'penyedia_id' => 5,
                'user_id' => 7,
                'is_published' => true,
                'published_at' => '2024-08-01 11:00:00',
            ],
            [
                'kode_paket' => 'PKT.2024.010',
                'nama_paket' => 'Pengadaan Peralatan Meja dan Kursi Kantor',
                'uraian_pekerjaan' => 'Pengadaan meja kerja, kursi kantor, lemari arsip, dan rak buku untuk kebutuhan operasional',
                'pagu_anggaran' => 180_000_000,
                'hps' => 178_000_000,
                'status' => 'disetujui',
                'unit_kerja_id' => 6,
                'tahun_anggaran_id' => 1,
                'program_id' => 1,
                'kegiatan_id' => 1,
                'sub_kegiatan_id' => 2,
                'sumber_dana_id' => 1,
                'jenis_pengadaan_id' => 1,
                'metode_pengadaan_id' => 4,
                'kategori_id' => 11,
                'satuan_id' => 1,
                'penyedia_id' => 12,
                'user_id' => 8,
                'is_published' => false,
                'published_at' => null,
            ],
            [
                'kode_paket' => 'PKT.2024.011',
                'nama_paket' => 'Jasa Kebersihan Kantor Tahun 2024',
                'uraian_pekerjaan' => 'Jasa kebersihan gedung kantor meliputi 10 lantai dengan luas total 5000m2 selama 12 bulan',
                'pagu_anggaran' => 120_000_000,
                'hps' => 118_000_000,
                'status' => 'dipublikasikan',
                'unit_kerja_id' => 6,
                'tahun_anggaran_id' => 1,
                'program_id' => 1,
                'kegiatan_id' => 2,
                'sub_kegiatan_id' => 3,
                'sumber_dana_id' => 1,
                'jenis_pengadaan_id' => 4,
                'metode_pengadaan_id' => 4,
                'kategori_id' => 3,
                'satuan_id' => 10,
                'penyedia_id' => 2,
                'user_id' => 8,
                'is_published' => true,
                'published_at' => '2024-01-02 08:00:00',
            ],
            [
                'kode_paket' => 'PKT.2024.012',
                'nama_paket' => 'Pengadaan Kendaraan Operasional Roda Empat',
                'uraian_pekerjaan' => 'Pengadaan 3 unit kendaraan operasional roda empat jenis MPV untuk dinas lapangan',
                'pagu_anggaran' => 450_000_000,
                'hps' => 445_000_000,
                'status' => 'dipublikasikan',
                'unit_kerja_id' => 1,
                'tahun_anggaran_id' => 1,
                'program_id' => 1,
                'kegiatan_id' => 1,
                'sub_kegiatan_id' => 1,
                'sumber_dana_id' => 1,
                'jenis_pengadaan_id' => 1,
                'metode_pengadaan_id' => 1,
                'kategori_id' => 10,
                'satuan_id' => 1,
                'penyedia_id' => 7,
                'user_id' => 3,
                'is_published' => true,
                'published_at' => '2024-09-15 09:00:00',
            ],
            [
                'kode_paket' => 'PKT.2024.013',
                'nama_paket' => 'Pengadaan AC Ruangan',
                'uraian_pekerjaan' => 'Pengadaan dan instalasi AC split 2 PK sebanyak 30 unit untuk ruangan kantor',
                'pagu_anggaran' => 200_000_000,
                'hps' => 196_000_000,
                'status' => 'disetujui',
                'unit_kerja_id' => 3,
                'tahun_anggaran_id' => 1,
                'program_id' => 1,
                'kegiatan_id' => 1,
                'sub_kegiatan_id' => 2,
                'sumber_dana_id' => 1,
                'jenis_pengadaan_id' => 1,
                'metode_pengadaan_id' => 4,
                'kategori_id' => 1,
                'satuan_id' => 1,
                'penyedia_id' => 4,
                'user_id' => 5,
                'is_published' => false,
                'published_at' => null,
            ],
            [
                'kode_paket' => 'PKT.2024.014',
                'nama_paket' => 'Jasa Konsultansi Audit Sistem Informasi',
                'uraian_pekerjaan' => 'Jasa konsultansi audit sistem informasi dan keamanan data untuk seluruh aplikasi dan infrastruktur TI',
                'pagu_anggaran' => 100_000_000,
                'hps' => 99_000_000,
                'status' => 'dipublikasikan',
                'unit_kerja_id' => 9,
                'tahun_anggaran_id' => 1,
                'program_id' => 2,
                'kegiatan_id' => 3,
                'sub_kegiatan_id' => 5,
                'sumber_dana_id' => 1,
                'jenis_pengadaan_id' => 3,
                'metode_pengadaan_id' => 3,
                'kategori_id' => 5,
                'satuan_id' => 3,
                'penyedia_id' => 10,
                'user_id' => 11,
                'is_published' => true,
                'published_at' => '2024-10-01 10:00:00',
            ],

            // ── 2025 (TA 2, programs 3-5) ──────────────────────────────────
            [
                'kode_paket' => 'PKT.2025.001',
                'nama_paket' => 'Bimbingan Teknis Pengadaan Barang dan Jasa',
                'uraian_pekerjaan' => 'Pelaksanaan bimbingan teknis pengadaan barang dan jasa pemerintah bagi 50 peserta selama 5 hari',
                'pagu_anggaran' => 300_000_000,
                'hps' => 295_000_000,
                'status' => 'dipublikasikan',
                'unit_kerja_id' => 4,
                'tahun_anggaran_id' => 2,
                'program_id' => 3,
                'kegiatan_id' => 5,
                'sub_kegiatan_id' => 9,
                'sumber_dana_id' => 1,
                'jenis_pengadaan_id' => 4,
                'metode_pengadaan_id' => 4,
                'kategori_id' => 5,
                'satuan_id' => 19,
                'penyedia_id' => 5,
                'user_id' => 6,
                'is_published' => true,
                'published_at' => '2025-03-01 09:00:00',
            ],
            [
                'kode_paket' => 'PKT.2025.002',
                'nama_paket' => 'Diklat Kepemimpinan Tingkat IV',
                'uraian_pekerjaan' => 'Penyelenggaraan pendidikan dan pelatihan kepemimpinan tingkat IV bagi 30 pegawai',
                'pagu_anggaran' => 200_000_000,
                'hps' => 197_000_000,
                'status' => 'disetujui',
                'unit_kerja_id' => 4,
                'tahun_anggaran_id' => 2,
                'program_id' => 3,
                'kegiatan_id' => 5,
                'sub_kegiatan_id' => 10,
                'sumber_dana_id' => 1,
                'jenis_pengadaan_id' => 4,
                'metode_pengadaan_id' => 4,
                'kategori_id' => 5,
                'satuan_id' => 19,
                'penyedia_id' => 14,
                'user_id' => 6,
                'is_published' => false,
                'published_at' => null,
            ],
            [
                'kode_paket' => 'PKT.2025.003',
                'nama_paket' => 'Sosialisasi Standar Pelayanan Publik',
                'uraian_pekerjaan' => 'Sosialisasi standar pelayanan publik kepada masyarakat dan stakeholder di 5 kecamatan',
                'pagu_anggaran' => 150_000_000,
                'hps' => 148_000_000,
                'status' => 'diverifikasi',
                'unit_kerja_id' => 8,
                'tahun_anggaran_id' => 2,
                'program_id' => 3,
                'kegiatan_id' => 6,
                'sub_kegiatan_id' => 11,
                'sumber_dana_id' => 1,
                'jenis_pengadaan_id' => 4,
                'metode_pengadaan_id' => 4,
                'kategori_id' => 5,
                'satuan_id' => 19,
                'penyedia_id' => null,
                'user_id' => 10,
                'is_published' => false,
                'published_at' => null,
            ],
            [
                'kode_paket' => 'PKT.2025.004',
                'nama_paket' => 'Pengadaan Alat Tulis Kantor Tahun 2025',
                'uraian_pekerjaan' => 'Pengadaan alat tulis kantor untuk kebutuhan seluruh unit kerja selama satu tahun anggaran',
                'pagu_anggaran' => 500_000_000,
                'hps' => 490_000_000,
                'status' => 'dipublikasikan',
                'unit_kerja_id' => 10,
                'tahun_anggaran_id' => 2,
                'program_id' => 4,
                'kegiatan_id' => 7,
                'sub_kegiatan_id' => 12,
                'sumber_dana_id' => 1,
                'jenis_pengadaan_id' => 1,
                'metode_pengadaan_id' => 10,
                'kategori_id' => 2,
                'satuan_id' => 3,
                'penyedia_id' => 8,
                'user_id' => 12,
                'is_published' => true,
                'published_at' => '2025-01-15 08:00:00',
            ],
            [
                'kode_paket' => 'PKT.2025.005',
                'nama_paket' => 'Jasa Kebersihan Kantor Tahun 2025',
                'uraian_pekerjaan' => 'Penyediaan jasa kebersihan untuk seluruh gedung kantor dengan 20 orang tenaga kebersihan selama 12 bulan',
                'pagu_anggaran' => 600_000_000,
                'hps' => 590_000_000,
                'status' => 'dipublikasikan',
                'unit_kerja_id' => 10,
                'tahun_anggaran_id' => 2,
                'program_id' => 4,
                'kegiatan_id' => 8,
                'sub_kegiatan_id' => 13,
                'sumber_dana_id' => 1,
                'jenis_pengadaan_id' => 4,
                'metode_pengadaan_id' => 1,
                'kategori_id' => 3,
                'satuan_id' => 10,
                'penyedia_id' => 2,
                'user_id' => 12,
                'is_published' => true,
                'published_at' => '2025-01-02 08:00:00',
            ],
            [
                'kode_paket' => 'PKT.2025.006',
                'nama_paket' => 'Jasa Keamanan Kantor Tahun 2025',
                'uraian_pekerjaan' => 'Penyediaan jasa keamanan dengan 15 orang tenaga satpam bersertifikat Gada Pratama selama 12 bulan',
                'pagu_anggaran' => 500_000_000,
                'hps' => 495_000_000,
                'status' => 'diverifikasi',
                'unit_kerja_id' => 10,
                'tahun_anggaran_id' => 2,
                'program_id' => 4,
                'kegiatan_id' => 8,
                'sub_kegiatan_id' => 14,
                'sumber_dana_id' => 1,
                'jenis_pengadaan_id' => 4,
                'metode_pengadaan_id' => 1,
                'kategori_id' => 4,
                'satuan_id' => 10,
                'penyedia_id' => null,
                'user_id' => 12,
                'is_published' => false,
                'published_at' => null,
            ],
            [
                'kode_paket' => 'PKT.2025.007',
                'nama_paket' => 'Rehabilitasi Total Gedung A',
                'uraian_pekerjaan' => 'Rehabilitasi total gedung A meliputi perbaikan struktur, atap, instalasi listrik, plumbing, dan finishing',
                'pagu_anggaran' => 1_500_000_000,
                'hps' => 1_475_000_000,
                'status' => 'disetujui',
                'unit_kerja_id' => 7,
                'tahun_anggaran_id' => 2,
                'program_id' => 5,
                'kegiatan_id' => 9,
                'sub_kegiatan_id' => 15,
                'sumber_dana_id' => 1,
                'jenis_pengadaan_id' => 2,
                'metode_pengadaan_id' => 1,
                'kategori_id' => 7,
                'satuan_id' => 3,
                'penyedia_id' => 3,
                'user_id' => 9,
                'is_published' => false,
                'published_at' => null,
            ],
            [
                'kode_paket' => 'PKT.2025.008',
                'nama_paket' => 'Peningkatan Jalan Akses Kantor',
                'uraian_pekerjaan' => 'Peningkatan kualitas jalan akses menuju kantor sepanjang 2,5 km dengan pengaspalan hotmix dan drainase',
                'pagu_anggaran' => 1_200_000_000,
                'hps' => 1_180_000_000,
                'status' => 'dipublikasikan',
                'unit_kerja_id' => 7,
                'tahun_anggaran_id' => 2,
                'program_id' => 5,
                'kegiatan_id' => 10,
                'sub_kegiatan_id' => 16,
                'sumber_dana_id' => 2,
                'jenis_pengadaan_id' => 2,
                'metode_pengadaan_id' => 1,
                'kategori_id' => 8,
                'satuan_id' => 3,
                'penyedia_id' => 3,
                'user_id' => 9,
                'is_published' => true,
                'published_at' => '2025-05-20 09:00:00',
            ],
            [
                'kode_paket' => 'PKT.2025.009',
                'nama_paket' => 'Pengadaan Furniture Kantor',
                'uraian_pekerjaan' => 'Pengadaan meja direksi, kursi tamu, sofa lobi, lemari arsip, dan rak display untuk ruang kerja',
                'pagu_anggaran' => 350_000_000,
                'hps' => 346_000_000,
                'status' => 'dipublikasikan',
                'unit_kerja_id' => 1,
                'tahun_anggaran_id' => 2,
                'program_id' => 4,
                'kegiatan_id' => 7,
                'sub_kegiatan_id' => 12,
                'sumber_dana_id' => 1,
                'jenis_pengadaan_id' => 1,
                'metode_pengadaan_id' => 1,
                'kategori_id' => 11,
                'satuan_id' => 1,
                'penyedia_id' => 12,
                'user_id' => 3,
                'is_published' => true,
                'published_at' => '2025-04-10 09:00:00',
            ],
            [
                'kode_paket' => 'PKT.2025.010',
                'nama_paket' => 'Jasa Konsultansi Pengawasan Rehabilitasi Gedung',
                'uraian_pekerjaan' => 'Jasa konsultansi pengawasan pelaksanaan rehabilitasi gedung A sesuai spesifikasi teknis yang ditentukan',
                'pagu_anggaran' => 200_000_000,
                'hps' => 197_000_000,
                'status' => 'diverifikasi',
                'unit_kerja_id' => 7,
                'tahun_anggaran_id' => 2,
                'program_id' => 5,
                'kegiatan_id' => 9,
                'sub_kegiatan_id' => 15,
                'sumber_dana_id' => 1,
                'jenis_pengadaan_id' => 3,
                'metode_pengadaan_id' => 5,
                'kategori_id' => 6,
                'satuan_id' => 3,
                'penyedia_id' => null,
                'user_id' => 9,
                'is_published' => false,
                'published_at' => null,
            ],
            [
                'kode_paket' => 'PKT.2025.011',
                'nama_paket' => 'Pengadaan Peralatan Kebersihan',
                'uraian_pekerjaan' => 'Pengadaan alat-alat kebersihan termasuk vacuum cleaner, mesin pembersih lantai, dan perlengkapan kebersihan lainnya',
                'pagu_anggaran' => 80_000_000,
                'hps' => 79_000_000,
                'status' => 'draft',
                'unit_kerja_id' => 6,
                'tahun_anggaran_id' => 2,
                'program_id' => 4,
                'kegiatan_id' => 8,
                'sub_kegiatan_id' => 13,
                'sumber_dana_id' => 1,
                'jenis_pengadaan_id' => 1,
                'metode_pengadaan_id' => 4,
                'kategori_id' => 3,
                'satuan_id' => 1,
                'penyedia_id' => null,
                'user_id' => 8,
                'is_published' => false,
                'published_at' => null,
            ],
            [
                'kode_paket' => 'PKT.2025.012',
                'nama_paket' => 'Percetakan dan Publikasi Dokumen',
                'uraian_pekerjaan' => 'Percetakan dokumen laporan tahunan, buku saku, brosur, dan spanduk untuk kebutuhan sosialisasi',
                'pagu_anggaran' => 120_000_000,
                'hps' => 118_000_000,
                'status' => 'diajukan',
                'unit_kerja_id' => 9,
                'tahun_anggaran_id' => 2,
                'program_id' => 4,
                'kegiatan_id' => 7,
                'sub_kegiatan_id' => 12,
                'sumber_dana_id' => 1,
                'jenis_pengadaan_id' => 4,
                'metode_pengadaan_id' => 4,
                'kategori_id' => 12,
                'satuan_id' => 3,
                'penyedia_id' => null,
                'user_id' => 11,
                'is_published' => false,
                'published_at' => null,
            ],
            [
                'kode_paket' => 'PKT.2025.013',
                'nama_paket' => 'Pengadaan Seragam Dinas Pegawai',
                'uraian_pekerjaan' => 'Pengadaan seragam dinas harian dan seragam lapangan untuk 200 pegawai',
                'pagu_anggaran' => 250_000_000,
                'hps' => 245_000_000,
                'status' => 'dikembalikan',
                'unit_kerja_id' => 4,
                'tahun_anggaran_id' => 2,
                'program_id' => 4,
                'kegiatan_id' => 7,
                'sub_kegiatan_id' => 12,
                'sumber_dana_id' => 1,
                'jenis_pengadaan_id' => 1,
                'metode_pengadaan_id' => 1,
                'kategori_id' => 14,
                'satuan_id' => 3,
                'penyedia_id' => null,
                'user_id' => 6,
                'is_published' => false,
                'published_at' => null,
            ],
            [
                'kode_paket' => 'PKT.2025.014',
                'nama_paket' => 'Jasa Konsultansi Penyusunan SOP',
                'uraian_pekerjaan' => 'Jasa konsultansi penyusunan standar operasional prosedur untuk seluruh unit kerja',
                'pagu_anggaran' => 100_000_000,
                'hps' => 99_000_000,
                'status' => 'diverifikasi',
                'unit_kerja_id' => 9,
                'tahun_anggaran_id' => 2,
                'program_id' => 3,
                'kegiatan_id' => 6,
                'sub_kegiatan_id' => 11,
                'sumber_dana_id' => 1,
                'jenis_pengadaan_id' => 3,
                'metode_pengadaan_id' => 3,
                'kategori_id' => 5,
                'satuan_id' => 3,
                'penyedia_id' => 10,
                'user_id' => 11,
                'is_published' => false,
                'published_at' => null,
            ],
            [
                'kode_paket' => 'PKT.2025.015',
                'nama_paket' => 'Pengadaan Buku Perpustakaan Digital',
                'uraian_pekerjaan' => 'Pengadaan koleksi buku digital dan e-book untuk perpustakaan kantor',
                'pagu_anggaran' => 75_000_000,
                'hps' => 74_000_000,
                'status' => 'dipublikasikan',
                'unit_kerja_id' => 9,
                'tahun_anggaran_id' => 2,
                'program_id' => 4,
                'kegiatan_id' => 7,
                'sub_kegiatan_id' => 12,
                'sumber_dana_id' => 1,
                'jenis_pengadaan_id' => 1,
                'metode_pengadaan_id' => 4,
                'kategori_id' => 13,
                'satuan_id' => 1,
                'penyedia_id' => 4,
                'user_id' => 11,
                'is_published' => true,
                'published_at' => '2025-08-01 09:00:00',
            ],
            [
                'kode_paket' => 'PKT.2025.016',
                'nama_paket' => 'Perawatan Gedung Kantor',
                'uraian_pekerjaan' => 'Perawatan rutin gedung kantor meliputi pengecatan, perbaikan atap bocor, dan perawatan instalasi listrik',
                'pagu_anggaran' => 150_000_000,
                'hps' => 148_000_000,
                'status' => 'disetujui',
                'unit_kerja_id' => 6,
                'tahun_anggaran_id' => 2,
                'program_id' => 4,
                'kegiatan_id' => 8,
                'sub_kegiatan_id' => 13,
                'sumber_dana_id' => 1,
                'jenis_pengadaan_id' => 2,
                'metode_pengadaan_id' => 4,
                'kategori_id' => 15,
                'satuan_id' => 3,
                'penyedia_id' => 3,
                'user_id' => 8,
                'is_published' => false,
                'published_at' => null,
            ],

            // ── 2026 (TA 3, programs 6-8) ──────────────────────────────────
            [
                'kode_paket' => 'PKT.2026.001',
                'nama_paket' => 'Pembangunan Portal Layanan Digital Terpadu',
                'uraian_pekerjaan' => 'Pembangunan portal layanan digital terpadu yang mengintegrasikan seluruh layanan publik secara online',
                'pagu_anggaran' => 1_500_000_000,
                'hps' => 1_475_000_000,
                'status' => 'draft',
                'unit_kerja_id' => 8,
                'tahun_anggaran_id' => 3,
                'program_id' => 6,
                'kegiatan_id' => 11,
                'sub_kegiatan_id' => 17,
                'sumber_dana_id' => 1,
                'jenis_pengadaan_id' => 3,
                'metode_pengadaan_id' => 5,
                'kategori_id' => 5,
                'satuan_id' => 3,
                'penyedia_id' => null,
                'user_id' => 10,
                'is_published' => false,
                'published_at' => null,
            ],
            [
                'kode_paket' => 'PKT.2026.002',
                'nama_paket' => 'Aplikasi Sistem Pengaduan Masyarakat',
                'uraian_pekerjaan' => 'Pengembangan aplikasi sistem pengaduan masyarakat berbasis mobile dengan fitur tracking dan notifikasi real-time',
                'pagu_anggaran' => 800_000_000,
                'hps' => 790_000_000,
                'status' => 'draft',
                'unit_kerja_id' => 8,
                'tahun_anggaran_id' => 3,
                'program_id' => 6,
                'kegiatan_id' => 11,
                'sub_kegiatan_id' => 18,
                'sumber_dana_id' => 4,
                'jenis_pengadaan_id' => 3,
                'metode_pengadaan_id' => 5,
                'kategori_id' => 5,
                'satuan_id' => 3,
                'penyedia_id' => null,
                'user_id' => 10,
                'is_published' => false,
                'published_at' => null,
            ],
            [
                'kode_paket' => 'PKT.2026.003',
                'nama_paket' => 'Pembangunan Gedung Data Center',
                'uraian_pekerjaan' => 'Pembangunan gedung data center tier 3 dengan sistem pendingin presisi, fire suppression, dan akses kontrol biometrik',
                'pagu_anggaran' => 1_200_000_000,
                'hps' => 1_180_000_000,
                'status' => 'draft',
                'unit_kerja_id' => 5,
                'tahun_anggaran_id' => 3,
                'program_id' => 6,
                'kegiatan_id' => 12,
                'sub_kegiatan_id' => 19,
                'sumber_dana_id' => 1,
                'jenis_pengadaan_id' => 2,
                'metode_pengadaan_id' => 1,
                'kategori_id' => 7,
                'satuan_id' => 3,
                'penyedia_id' => null,
                'user_id' => 7,
                'is_published' => false,
                'published_at' => null,
            ],
            [
                'kode_paket' => 'PKT.2026.004',
                'nama_paket' => 'Pengadaan UPS dan Genset Data Center',
                'uraian_pekerjaan' => 'Pengadaan UPS 500kVA dan genset 1000kVA untuk kebutuhan listrik cadangan data center',
                'pagu_anggaran' => 500_000_000,
                'hps' => 495_000_000,
                'status' => 'draft',
                'unit_kerja_id' => 5,
                'tahun_anggaran_id' => 3,
                'program_id' => 6,
                'kegiatan_id' => 12,
                'sub_kegiatan_id' => 20,
                'sumber_dana_id' => 1,
                'jenis_pengadaan_id' => 1,
                'metode_pengadaan_id' => 1,
                'kategori_id' => 1,
                'satuan_id' => 1,
                'penyedia_id' => null,
                'user_id' => 7,
                'is_published' => false,
                'published_at' => null,
            ],
            [
                'kode_paket' => 'PKT.2026.005',
                'nama_paket' => 'Pembangunan Gedung Serbaguna',
                'uraian_pekerjaan' => 'Pembangunan gedung serbaguna 3 lantai dengan kapasitas 500 orang, ruang rapat, dan fasilitas penunjang',
                'pagu_anggaran' => 2_500_000_000,
                'hps' => 2_450_000_000,
                'status' => 'diajukan',
                'unit_kerja_id' => 7,
                'tahun_anggaran_id' => 3,
                'program_id' => 7,
                'kegiatan_id' => 13,
                'sub_kegiatan_id' => 21,
                'sumber_dana_id' => 1,
                'jenis_pengadaan_id' => 2,
                'metode_pengadaan_id' => 1,
                'kategori_id' => 7,
                'satuan_id' => 3,
                'penyedia_id' => null,
                'user_id' => 9,
                'is_published' => false,
                'published_at' => null,
            ],
            [
                'kode_paket' => 'PKT.2026.006',
                'nama_paket' => 'Pengadaan Laptop ASN Tahun 2026',
                'uraian_pekerjaan' => 'Pengadaan 150 unit laptop notebook untuk pegawai di lingkungan unit kerja',
                'pagu_anggaran' => 750_000_000,
                'hps' => 742_500_000,
                'status' => 'draft',
                'unit_kerja_id' => 5,
                'tahun_anggaran_id' => 3,
                'program_id' => 8,
                'kegiatan_id' => 14,
                'sub_kegiatan_id' => 22,
                'sumber_dana_id' => 1,
                'jenis_pengadaan_id' => 1,
                'metode_pengadaan_id' => 1,
                'kategori_id' => 1,
                'satuan_id' => 1,
                'penyedia_id' => null,
                'user_id' => 7,
                'is_published' => false,
                'published_at' => null,
            ],
            [
                'kode_paket' => 'PKT.2026.007',
                'nama_paket' => 'Pengadaan Perangkat Multimedia Aula',
                'uraian_pekerjaan' => 'Pengadaan perangkat multimedia untuk aula pertemuan meliputi proyektor, sound system, dan layar presentasi',
                'pagu_anggaran' => 200_000_000,
                'hps' => 197_000_000,
                'status' => 'draft',
                'unit_kerja_id' => 8,
                'tahun_anggaran_id' => 3,
                'program_id' => 6,
                'kegiatan_id' => 11,
                'sub_kegiatan_id' => 17,
                'sumber_dana_id' => 4,
                'jenis_pengadaan_id' => 1,
                'metode_pengadaan_id' => 4,
                'kategori_id' => 1,
                'satuan_id' => 3,
                'penyedia_id' => null,
                'user_id' => 10,
                'is_published' => false,
                'published_at' => null,
            ],
            [
                'kode_paket' => 'PKT.2026.008',
                'nama_paket' => 'Jasa Konsultansi Manajemen Reformasi Birokrasi',
                'uraian_pekerjaan' => 'Jasa konsultansi pendampingan reformasi birokrasi dan penyusunan road map RB periode 2026-2028',
                'pagu_anggaran' => 200_000_000,
                'hps' => 197_000_000,
                'status' => 'draft',
                'unit_kerja_id' => 9,
                'tahun_anggaran_id' => 3,
                'program_id' => 8,
                'kegiatan_id' => 14,
                'sub_kegiatan_id' => 22,
                'sumber_dana_id' => 1,
                'jenis_pengadaan_id' => 3,
                'metode_pengadaan_id' => 5,
                'kategori_id' => 5,
                'satuan_id' => 3,
                'penyedia_id' => null,
                'user_id' => 11,
                'is_published' => false,
                'published_at' => null,
            ],
            [
                'kode_paket' => 'PKT.2026.009',
                'nama_paket' => 'Monitoring dan Evaluasi Kinerja Tahun 2026',
                'uraian_pekerjaan' => 'Kegiatan monitoring dan evaluasi kinerja seluruh unit kerja termasuk survei kepuasan dan pengukuran IKU',
                'pagu_anggaran' => 150_000_000,
                'hps' => 148_000_000,
                'status' => 'draft',
                'unit_kerja_id' => 4,
                'tahun_anggaran_id' => 3,
                'program_id' => 8,
                'kegiatan_id' => 14,
                'sub_kegiatan_id' => 24,
                'sumber_dana_id' => 1,
                'jenis_pengadaan_id' => 4,
                'metode_pengadaan_id' => 4,
                'kategori_id' => 5,
                'satuan_id' => 19,
                'penyedia_id' => null,
                'user_id' => 6,
                'is_published' => false,
                'published_at' => null,
            ],
            [
                'kode_paket' => 'PKT.2026.010',
                'nama_paket' => 'Sertifikasi Sistem Manajemen Mutu ISO',
                'uraian_pekerjaan' => 'Jasa konsultansi dan sertifikasi ISO 9001:2015 untuk sistem manajemen mutu institusi',
                'pagu_anggaran' => 200_000_000,
                'hps' => 197_000_000,
                'status' => 'draft',
                'unit_kerja_id' => 9,
                'tahun_anggaran_id' => 3,
                'program_id' => 8,
                'kegiatan_id' => 15,
                'sub_kegiatan_id' => 24,
                'sumber_dana_id' => 1,
                'jenis_pengadaan_id' => 3,
                'metode_pengadaan_id' => 7,
                'kategori_id' => 5,
                'satuan_id' => 3,
                'penyedia_id' => null,
                'user_id' => 11,
                'is_published' => false,
                'published_at' => null,
            ],
            [
                'kode_paket' => 'PKT.2026.011',
                'nama_paket' => 'Pengadaan Kendaraan Dinas Baru',
                'uraian_pekerjaan' => 'Pengadaan 5 unit kendaraan dinas roda empat untuk operasional pimpinan dan staf',
                'pagu_anggaran' => 800_000_000,
                'hps' => 792_000_000,
                'status' => 'diajukan',
                'unit_kerja_id' => 1,
                'tahun_anggaran_id' => 3,
                'program_id' => 7,
                'kegiatan_id' => 13,
                'sub_kegiatan_id' => 21,
                'sumber_dana_id' => 1,
                'jenis_pengadaan_id' => 1,
                'metode_pengadaan_id' => 1,
                'kategori_id' => 10,
                'satuan_id' => 1,
                'penyedia_id' => null,
                'user_id' => 3,
                'is_published' => false,
                'published_at' => null,
            ],
            [
                'kode_paket' => 'PKT.2026.012',
                'nama_paket' => 'Jasa Konsultansi Perencanaan Gedung Serbaguna',
                'uraian_pekerjaan' => 'Jasa konsultansi perencanaan dan perancangan gedung serbaguna termasuk DED, RAB, dan dokumen tender',
                'pagu_anggaran' => 350_000_000,
                'hps' => 345_000_000,
                'status' => 'draft',
                'unit_kerja_id' => 7,
                'tahun_anggaran_id' => 3,
                'program_id' => 7,
                'kegiatan_id' => 13,
                'sub_kegiatan_id' => 21,
                'sumber_dana_id' => 1,
                'jenis_pengadaan_id' => 3,
                'metode_pengadaan_id' => 5,
                'kategori_id' => 6,
                'satuan_id' => 3,
                'penyedia_id' => null,
                'user_id' => 9,
                'is_published' => false,
                'published_at' => null,
            ],
            [
                'kode_paket' => 'PKT.2026.013',
                'nama_paket' => 'Pengadaan Mebel Kantor Baru',
                'uraian_pekerjaan' => 'Pengadaan meja, kursi, lemari, dan rak untuk kebutuhan pegawai baru dan penggantian inventaris rusak',
                'pagu_anggaran' => 250_000_000,
                'hps' => 247_000_000,
                'status' => 'draft',
                'unit_kerja_id' => 2,
                'tahun_anggaran_id' => 3,
                'program_id' => 7,
                'kegiatan_id' => 13,
                'sub_kegiatan_id' => 21,
                'sumber_dana_id' => 1,
                'jenis_pengadaan_id' => 1,
                'metode_pengadaan_id' => 1,
                'kategori_id' => 11,
                'satuan_id' => 1,
                'penyedia_id' => null,
                'user_id' => 4,
                'is_published' => false,
                'published_at' => null,
            ],
            [
                'kode_paket' => 'PKT.2026.014',
                'nama_paket' => 'Jasa Kebersihan Kantor Tahun 2026',
                'uraian_pekerjaan' => 'Penyediaan jasa kebersihan untuk seluruh gedung kantor dengan 22 orang tenaga kebersihan selama 12 bulan',
                'pagu_anggaran' => 650_000_000,
                'hps' => 640_000_000,
                'status' => 'draft',
                'unit_kerja_id' => 10,
                'tahun_anggaran_id' => 3,
                'program_id' => 7,
                'kegiatan_id' => 13,
                'sub_kegiatan_id' => 21,
                'sumber_dana_id' => 1,
                'jenis_pengadaan_id' => 4,
                'metode_pengadaan_id' => 1,
                'kategori_id' => 3,
                'satuan_id' => 10,
                'penyedia_id' => null,
                'user_id' => 12,
                'is_published' => false,
                'published_at' => null,
            ],
            [
                'kode_paket' => 'PKT.2026.015',
                'nama_paket' => 'Jasa Keamanan Kantor Tahun 2026',
                'uraian_pekerjaan' => 'Penyediaan jasa keamanan dengan 18 orang tenaga satpam bersertifikat Gada Pratama selama 12 bulan',
                'pagu_anggaran' => 550_000_000,
                'hps' => 545_000_000,
                'status' => 'draft',
                'unit_kerja_id' => 10,
                'tahun_anggaran_id' => 3,
                'program_id' => 7,
                'kegiatan_id' => 13,
                'sub_kegiatan_id' => 21,
                'sumber_dana_id' => 1,
                'jenis_pengadaan_id' => 4,
                'metode_pengadaan_id' => 1,
                'kategori_id' => 4,
                'satuan_id' => 10,
                'penyedia_id' => null,
                'user_id' => 12,
                'is_published' => false,
                'published_at' => null,
            ],
            [
                'kode_paket' => 'PKT.2026.016',
                'nama_paket' => 'Pengadaan ATK Semester I Tahun 2026',
                'uraian_pekerjaan' => 'Pengadaan alat tulis kantor untuk kebutuhan semester pertama seluruh unit kerja',
                'pagu_anggaran' => 250_000_000,
                'hps' => 247_000_000,
                'status' => 'draft',
                'unit_kerja_id' => 10,
                'tahun_anggaran_id' => 3,
                'program_id' => 8,
                'kegiatan_id' => 14,
                'sub_kegiatan_id' => 22,
                'sumber_dana_id' => 1,
                'jenis_pengadaan_id' => 1,
                'metode_pengadaan_id' => 10,
                'kategori_id' => 2,
                'satuan_id' => 3,
                'penyedia_id' => null,
                'user_id' => 12,
                'is_published' => false,
                'published_at' => null,
            ],
            [
                'kode_paket' => 'PKT.2026.017',
                'nama_paket' => 'Pengadaan ATK Semester II Tahun 2026',
                'uraian_pekerjaan' => 'Pengadaan alat tulis kantor untuk kebutuhan semester kedua seluruh unit kerja',
                'pagu_anggaran' => 250_000_000,
                'hps' => 247_000_000,
                'status' => 'draft',
                'unit_kerja_id' => 10,
                'tahun_anggaran_id' => 3,
                'program_id' => 8,
                'kegiatan_id' => 14,
                'sub_kegiatan_id' => 22,
                'sumber_dana_id' => 1,
                'jenis_pengadaan_id' => 1,
                'metode_pengadaan_id' => 10,
                'kategori_id' => 2,
                'satuan_id' => 3,
                'penyedia_id' => null,
                'user_id' => 12,
                'is_published' => false,
                'published_at' => null,
            ],
            [
                'kode_paket' => 'PKT.2026.018',
                'nama_paket' => 'Jasa Konsultansi Pengawasan Pembangunan Gedung',
                'uraian_pekerjaan' => 'Jasa konsultansi pengawasan pembangunan gedung serbaguna 3 lantai termasuk MEP dan landscape',
                'pagu_anggaran' => 300_000_000,
                'hps' => 296_000_000,
                'status' => 'draft',
                'unit_kerja_id' => 7,
                'tahun_anggaran_id' => 3,
                'program_id' => 7,
                'kegiatan_id' => 13,
                'sub_kegiatan_id' => 21,
                'sumber_dana_id' => 1,
                'jenis_pengadaan_id' => 3,
                'metode_pengadaan_id' => 5,
                'kategori_id' => 6,
                'satuan_id' => 3,
                'penyedia_id' => null,
                'user_id' => 9,
                'is_published' => false,
                'published_at' => null,
            ],
            [
                'kode_paket' => 'PKT.2026.019',
                'nama_paket' => 'Pengadaan Peralatan Laboratorium Komputer',
                'uraian_pekerjaan' => 'Pengadaan 40 unit PC workstation, monitor, dan peralatan laboratorium komputer untuk pelatihan',
                'pagu_anggaran' => 400_000_000,
                'hps' => 395_000_000,
                'status' => 'diajukan',
                'unit_kerja_id' => 5,
                'tahun_anggaran_id' => 3,
                'program_id' => 6,
                'kegiatan_id' => 12,
                'sub_kegiatan_id' => 19,
                'sumber_dana_id' => 1,
                'jenis_pengadaan_id' => 1,
                'metode_pengadaan_id' => 1,
                'kategori_id' => 1,
                'satuan_id' => 1,
                'penyedia_id' => null,
                'user_id' => 7,
                'is_published' => false,
                'published_at' => null,
            ],
            [
                'kode_paket' => 'PKT.2026.020',
                'nama_paket' => 'Pengadaan Perangkat Telekomunikasi',
                'uraian_pekerjaan' => 'Pengadaan perangkat telekomunikasi PABX, handset, dan interkom untuk sistem komunikasi kantor',
                'pagu_anggaran' => 150_000_000,
                'hps' => 148_000_000,
                'status' => 'draft',
                'unit_kerja_id' => 5,
                'tahun_anggaran_id' => 3,
                'program_id' => 6,
                'kegiatan_id' => 11,
                'sub_kegiatan_id' => 17,
                'sumber_dana_id' => 1,
                'jenis_pengadaan_id' => 1,
                'metode_pengadaan_id' => 4,
                'kategori_id' => 1,
                'satuan_id' => 1,
                'penyedia_id' => null,
                'user_id' => 7,
                'is_published' => false,
                'published_at' => null,
            ],
            [
                'kode_paket' => 'PKT.2026.021',
                'nama_paket' => 'Layanan Internet dan Jaringan Tahun 2026',
                'uraian_pekerjaan' => 'Penyediaan layanan internet dedicated 100Mbps dan pemeliharaan jaringan lokal selama 12 bulan',
                'pagu_anggaran' => 300_000_000,
                'hps' => 296_000_000,
                'status' => 'draft',
                'unit_kerja_id' => 5,
                'tahun_anggaran_id' => 3,
                'program_id' => 6,
                'kegiatan_id' => 11,
                'sub_kegiatan_id' => 17,
                'sumber_dana_id' => 1,
                'jenis_pengadaan_id' => 4,
                'metode_pengadaan_id' => 1,
                'kategori_id' => 1,
                'satuan_id' => 10,
                'penyedia_id' => null,
                'user_id' => 7,
                'is_published' => false,
                'published_at' => null,
            ],
            [
                'kode_paket' => 'PKT.2026.022',
                'nama_paket' => 'Pengadaan Peralatan P3K dan Kesehatan',
                'uraian_pekerjaan' => 'Pengadaan perlengkapan P3K, alat kesehatan dasar, dan perlengkapan ruang kesehatan kantor',
                'pagu_anggaran' => 120_000_000,
                'hps' => 118_500_000,
                'status' => 'draft',
                'unit_kerja_id' => 6,
                'tahun_anggaran_id' => 3,
                'program_id' => 7,
                'kegiatan_id' => 13,
                'sub_kegiatan_id' => 21,
                'sumber_dana_id' => 1,
                'jenis_pengadaan_id' => 1,
                'metode_pengadaan_id' => 4,
                'kategori_id' => 9,
                'satuan_id' => 3,
                'penyedia_id' => null,
                'user_id' => 8,
                'is_published' => false,
                'published_at' => null,
            ],
            [
                'kode_paket' => 'PKT.2026.023',
                'nama_paket' => 'Pengadaan Aplikasi Manajemen Aset',
                'uraian_pekerjaan' => 'Pengembangan aplikasi manajemen aset berbasis web untuk inventarisasi dan monitoring aset',
                'pagu_anggaran' => 300_000_000,
                'hps' => 296_000_000,
                'status' => 'draft',
                'unit_kerja_id' => 5,
                'tahun_anggaran_id' => 3,
                'program_id' => 8,
                'kegiatan_id' => 14,
                'sub_kegiatan_id' => 23,
                'sumber_dana_id' => 1,
                'jenis_pengadaan_id' => 3,
                'metode_pengadaan_id' => 5,
                'kategori_id' => 5,
                'satuan_id' => 3,
                'penyedia_id' => null,
                'user_id' => 7,
                'is_published' => false,
                'published_at' => null,
            ],
        ];

        // Mapping pejabat IDs: PPTK=unit*3-2, PP=unit*3-1, PA_KPA=unit*3
        $pktIds = [];
        foreach ($pakets as $i => $pkt) {
            $unitId = $pkt['unit_kerja_id'];
            $pkt['pptk_id'] = ($unitId - 1) * 3 + 1;
            $pkt['pp_id'] = ($unitId - 1) * 3 + 2;
            $pkt['pa_kpa_id'] = ($unitId - 1) * 3 + 3;
            $pkt['created_at'] = $now;
            $pkt['updated_at'] = $now;

            $pktId = DB::table('paket_pengadaans')->insertGetId($pkt);
            $pktIds[] = $pktId;
        }

        // ─── PAKET ANGGARAN ────────────────────────────────────────────────
        $anggaranItems = [];

        $anggaranTemplates = [
            // [paketIndexOffset, items...] each item = [nama_item, volume, satuan_id, harga_satuan]
            0 => [ // PKT.2024.001 - Laptop
                ['Laptop Notebook Core i5 16GB 512GB', 100, 1, 4_950_000],
            ],
            1 => [ // PKT.2024.002 - Printer
                ['Printer Multifungsi A3 Color', 15, 1, 8_500_000],
                ['Scanner Dokumen A3', 10, 1, 6_500_000],
            ],
            2 => [ // PKT.2024.003 - Renovasi
                ['Pengecatan Dinding', 1, 3, 150_000_000],
                ['Penggantian Plafon', 1, 3, 100_000_000],
                ['Instalasi Listrik', 1, 3, 80_000_000],
                ['Penggantian Lantai', 1, 3, 60_000_000],
            ],
            3 => [ // PKT.2024.004 - Arsip
                ['Pembangunan Ruang Arsip', 1, 3, 250_000_000],
                ['Sistem Penyimpanan Digital', 1, 3, 60_000_000],
                ['AC dan Pengatur Suhu', 2, 1, 17_500_000],
            ],
            4 => [ // PKT.2024.005 - SI Kepegawaian
                ['Pengembangan Aplikasi', 1, 3, 400_000_000],
                ['Server dan Database', 1, 3, 100_000_000],
                ['Integrasi Sistem', 1, 3, 85_000_000],
            ],
            5 => [ // PKT.2024.006 - Aplikasi Publik
                ['Pengembangan Mobile App', 1, 3, 250_000_000],
                ['Pengembangan Web App', 1, 3, 140_000_000],
            ],
            6 => [ // PKT.2024.007 - Server
                ['Server Blade', 4, 1, 85_000_000],
                ['Storage Area Network', 1, 1, 120_000_000],
                ['Switch SAN', 2, 1, 25_000_000],
            ],
            7 => [ // PKT.2024.008 - Jaringan
                ['Switch Core Layer 3', 5, 1, 25_000_000],
                ['Access Point Enterprise', 20, 1, 3_500_000],
                ['Kabel dan Konektor', 1, 3, 30_000_000],
            ],
            8 => [ // PKT.2024.009 - Kons Perencanaan
                ['Jasa Konsultansi Perencanaan TI', 1, 3, 148_500_000],
            ],
            9 => [ // PKT.2024.010 - Mebel
                ['Meja Kerja 1/2 Biro', 50, 1, 1_800_000],
                ['Kursi Kerja Ergonomic', 50, 1, 1_200_000],
                ['Lemari Arsip Besi', 20, 1, 1_200_000],
            ],
            10 => [ // PKT.2024.011 - Kebersihan
                ['Jasa Kebersihan 12 Bulan', 12, 10, 9_833_333],
            ],
            11 => [ // PKT.2024.012 - Kendaraan
                ['MPV 7-Seater', 3, 1, 148_333_333],
            ],
            12 => [ // PKT.2024.013 - AC
                ['AC Split 2 PK', 30, 1, 6_533_333],
            ],
            13 => [ // PKT.2024.014 - Audit
                ['Jasa Audit Sistem Informasi', 1, 3, 99_000_000],
            ],

            // 2025
            14 => [ // PKT.2025.001 - Bimtek
                ['Honor Narasumber', 5, 22, 5_000_000],
                ['Konsumsi Peserta', 50, 22, 150_000],
                ['Sewa Tempat', 5, 12, 15_000_000],
                ['Modul dan ATK', 50, 21, 200_000],
            ],
            15 => [ // PKT.2025.002 - Diklat
                ['Pelatihan Kepemimpinan', 30, 21, 6_566_667],
            ],
            16 => [ // PKT.2025.003 - Sosialisasi
                ['Sosialisasi di 5 Kecamatan', 5, 19, 29_600_000],
            ],
            17 => [ // PKT.2025.004 - ATK
                ['Paket ATK Besar', 500, 3, 980_000],
            ],
            18 => [ // PKT.2025.005 - Kebersihan
                ['Jasa Kebersihan 12 Bulan', 12, 10, 49_166_667],
            ],
            19 => [ // PKT.2025.006 - Keamanan
                ['Jasa Keamanan 12 Bulan', 12, 10, 41_250_000],
            ],
            20 => [ // PKT.2025.007 - Rehab Gedung
                ['Perbaikan Struktur', 1, 3, 500_000_000],
                ['Atap dan Plafon', 1, 3, 350_000_000],
                ['Instalasi Listrik dan Plumbing', 1, 3, 300_000_000],
                ['Finishing dan Cat', 1, 3, 325_000_000],
            ],
            21 => [ // PKT.2025.008 - Jalan
                ['Pengaspalan Hotmix', 2500, 7, 400_000],
                ['Drainase', 2500, 7, 72_000],
            ],
            22 => [ // PKT.2025.009 - Furniture
                ['Meja Direksi', 10, 1, 8_000_000],
                ['Kursi Tamu', 20, 1, 3_500_000],
                ['Sofa Lobi', 5, 1, 12_000_000],
                ['Lemari Arsip', 15, 1, 3_500_000],
            ],
            23 => [ // PKT.2025.010 - Kons Pengawasan
                ['Jasa Pengawasan Rehab Gedung', 1, 3, 197_000_000],
            ],
            24 => [ // PKT.2025.011 - Kebersihan
                ['Vacuum Cleaner Industrial', 5, 1, 5_000_000],
                ['Mesin Pembersih Lantai', 2, 1, 15_000_000],
                ['Perlengkapan Kebersihan', 1, 3, 24_000_000],
            ],
            25 => [ // PKT.2025.012 - Percetakan
                ['Cetak Laporan Tahunan', 500, 14, 100_000],
                ['Cetak Brosur', 5000, 14, 5_000],
                ['Spanduk dan Banner', 50, 14, 350_000],
            ],
            26 => [ // PKT.2025.013 - Seragam
                ['Seragam Dinas Harian', 200, 1, 850_000],
                ['Seragam Lapangan', 200, 1, 375_000],
            ],
            27 => [ // PKT.2025.014 - Kons SOP
                ['Jasa Konsultansi SOP', 1, 3, 99_000_000],
            ],
            28 => [ // PKT.2025.015 - Buku
                ['E-Book Koleksi Digital', 500, 1, 148_000],
            ],
            29 => [ // PKT.2025.016 - Perawatan
                ['Pengecatan Gedung', 1, 3, 60_000_000],
                ['Perbaikan Atap', 1, 3, 50_000_000],
                ['Perawatan Instalasi Listrik', 1, 3, 38_000_000],
            ],

            // 2026
            30 => [ // PKT.2026.001 - Portal
                ['Jasa Konsultansi Portal Digital', 1, 3, 1_475_000_000],
            ],
            31 => [ // PKT.2026.002 - Aplikasi Pengaduan
                ['Pengembangan Aplikasi Mobile', 1, 3, 500_000_000],
                ['Pengembangan Backend', 1, 3, 290_000_000],
            ],
            32 => [ // PKT.2026.003 - Data Center
                ['Pembangunan Gedung DC', 1, 3, 1_000_000_000],
                ['Fire Suppression System', 1, 3, 100_000_000],
                ['Access Control Biometric', 1, 3, 80_000_000],
            ],
            33 => [ // PKT.2026.004 - UPS Genset
                ['UPS 500kVA', 1, 1, 300_000_000],
                ['Genset 1000kVA', 1, 1, 195_000_000],
            ],
            34 => [ // PKT.2026.005 - Gedung Serbaguna
                ['Konstruksi Gedung 3 Lantai', 1, 3, 2_200_000_000],
                ['MEP dan Lift', 1, 3, 250_000_000],
            ],
            35 => [ // PKT.2026.006 - Laptop 2026
                ['Laptop Notebook Core i7 32GB 1TB', 150, 1, 4_950_000],
            ],
            36 => [ // PKT.2026.007 - Multimedia
                ['Proyektor Laser 4K', 3, 1, 35_000_000],
                ['Sound System Aula', 1, 3, 50_000_000],
                ['Layar Presentasi Motorized', 3, 1, 14_000_000],
            ],
            37 => [ // PKT.2026.008 - Kons RB
                ['Jasa Konsultansi Reformasi Birokrasi', 1, 3, 197_000_000],
            ],
            38 => [ // PKT.2026.009 - Monev
                ['Survei Kepuasan', 1, 19, 50_000_000],
                ['Pengukuran IKU', 1, 19, 50_000_000],
                ['Pelaporan', 1, 19, 48_000_000],
            ],
            39 => [ // PKT.2026.010 - ISO
                ['Jasa Konsultansi ISO 9001', 1, 3, 120_000_000],
                ['Biaya Sertifikasi', 1, 3, 77_000_000],
            ],
            40 => [ // PKT.2026.011 - Kendaraan
                ['Kendaraan Dinas MPV', 5, 1, 158_400_000],
            ],
            41 => [ // PKT.2026.012 - Kons Perencanaan
                ['Jasa Perencanaan Gedung', 1, 3, 345_000_000],
            ],
            42 => [ // PKT.2026.013 - Mebel
                ['Meja Kerja', 60, 1, 2_000_000],
                ['Kursi Kerja', 60, 1, 1_500_000],
                ['Lemari Arsip', 25, 1, 1_500_000],
                ['Rak Buku', 15, 1, 1_200_000],
            ],
            43 => [ // PKT.2026.014 - Kebersihan
                ['Jasa Kebersihan 12 Bulan', 12, 10, 53_333_333],
            ],
            44 => [ // PKT.2026.015 - Keamanan
                ['Jasa Keamanan 12 Bulan', 12, 10, 45_416_667],
            ],
            45 => [ // PKT.2026.016 - ATK I
                ['Paket ATK Semester I', 250, 3, 988_000],
            ],
            46 => [ // PKT.2026.017 - ATK II
                ['Paket ATK Semester II', 250, 3, 988_000],
            ],
            47 => [ // PKT.2026.018 - Kons Pengawasan
                ['Jasa Pengawasan Pembangunan', 1, 3, 296_000_000],
            ],
            48 => [ // PKT.2026.019 - Lab Komputer
                ['PC Workstation', 40, 1, 7_500_000],
                ['Monitor 24"', 40, 1, 2_000_000],
                ['UPS PC', 40, 1, 500_000],
            ],
            49 => [ // PKT.2026.020 - Telekomunikasi
                ['PABX System', 1, 1, 80_000_000],
                ['Handset Digital', 50, 1, 800_000],
                ['Interkom System', 1, 3, 28_000_000],
            ],
            50 => [ // PKT.2026.021 - Internet
                ['Internet Dedicated 100Mbps', 12, 10, 24_666_667],
            ],
            51 => [ // PKT.2026.022 - P3K
                ['APAR 4kg', 20, 1, 500_000],
                ['Kotak P3K Besar', 15, 1, 350_000],
                ['Tandu dan Alat Kesehatan', 5, 1, 2_500_000],
                ['Tensimeter Digital', 10, 1, 500_000],
            ],
            52 => [ // PKT.2026.023 - Aplikasi Aset
                ['Pengembangan Aplikasi Aset', 1, 3, 200_000_000],
                ['Database dan Server', 1, 3, 96_000_000],
            ],
        ];

        foreach ($anggaranTemplates as $pktIdx => $items) {
            $pktId = $pktIds[$pktIdx];
            foreach ($items as $item) {
                $total = $item[1] * $item[3];
                DB::table('paket_anggarans')->insert([
                    'paket_pengadaan_id' => $pktId,
                    'nama_item' => $item[0],
                    'volume' => $item[1],
                    'satuan_id' => $item[2],
                    'harga_satuan' => $item[3],
                    'total' => $total,
                    'created_at' => $now,
                    'updated_at' => $now,
                ]);
            }
        }

        // ─── PAKET JADWAL ──────────────────────────────────────────────────
        $jadwalTemplates = [
            0 => [['Perencanaan', '2024-01-01', '2024-01-31'], ['Persiapan', '2024-02-01', '2024-02-15'], ['Pemilihan', '2024-02-16', '2024-03-15'], ['Pelaksanaan', '2024-03-16', '2024-05-15']],
            1 => [['Perencanaan', '2024-02-01', '2024-02-20'], ['Pemilihan', '2024-02-21', '2024-03-10'], ['Pelaksanaan', '2024-03-11', '2024-04-10']],
            2 => [['Perencanaan', '2024-03-01', '2024-03-20'], ['Pemilihan', '2024-03-21', '2024-04-20'], ['Pelaksanaan', '2024-04-21', '2024-07-20']],
            3 => [['Perencanaan', '2024-04-01', '2024-04-20'], ['Pemilihan', '2024-04-21', '2024-05-15'], ['Pelaksanaan', '2024-05-16', '2024-08-15']],
            4 => [['Perencanaan', '2024-05-01', '2024-05-20'], ['Pemilihan', '2024-05-21', '2024-06-20'], ['Pelaksanaan', '2024-06-21', '2024-10-20']],
            5 => [['Perencanaan', '2024-06-01', '2024-06-15'], ['Pemilihan', '2024-06-16', '2024-07-15'], ['Pelaksanaan', '2024-07-16', '2024-10-15']],
            6 => [['Perencanaan', '2024-06-01', '2024-06-20'], ['Pemilihan', '2024-06-21', '2024-07-20'], ['Pelaksanaan', '2024-07-21', '2024-09-20']],
            7 => [['Perencanaan', '2024-06-15', '2024-07-05'], ['Pemilihan', '2024-07-06', '2024-07-25'], ['Pelaksanaan', '2024-07-26', '2024-09-25']],
            8 => [['Perencanaan', '2024-07-01', '2024-07-15'], ['Pemilihan', '2024-07-16', '2024-08-05'], ['Pelaksanaan', '2024-08-06', '2024-09-05']],
            9 => [['Perencanaan', '2024-08-01', '2024-08-15'], ['Pemilihan', '2024-08-16', '2024-09-05'], ['Pelaksanaan', '2024-09-06', '2024-10-05']],
            10 => [['Perencanaan', '2023-12-15', '2023-12-31'], ['Pemilihan', '2024-01-01', '2024-01-10'], ['Pelaksanaan', '2024-01-11', '2024-12-31']],
            11 => [['Perencanaan', '2024-08-01', '2024-08-20'], ['Pemilihan', '2024-08-21', '2024-09-10'], ['Pelaksanaan', '2024-09-11', '2024-10-10']],
            12 => [['Perencanaan', '2024-09-01', '2024-09-15'], ['Pemilihan', '2024-09-16', '2024-10-05'], ['Pelaksanaan', '2024-10-06', '2024-11-05']],
            13 => [['Perencanaan', '2024-09-01', '2024-09-15'], ['Pemilihan', '2024-09-16', '2024-10-01'], ['Pelaksanaan', '2024-10-02', '2024-11-01']],
            14 => [['Perencanaan', '2025-01-01', '2025-01-20'], ['Pemilihan', '2025-01-21', '2025-02-10'], ['Pelaksanaan', '2025-02-11', '2025-03-11']],
            15 => [['Perencanaan', '2025-02-01', '2025-02-15'], ['Pemilihan', '2025-02-16', '2025-03-05'], ['Pelaksanaan', '2025-03-06', '2025-04-05']],
            16 => [['Perencanaan', '2025-02-01', '2025-02-15'], ['Pemilihan', '2025-02-16', '2025-03-05'], ['Pelaksanaan', '2025-03-06', '2025-04-05']],
            17 => [['Perencanaan', '2024-12-01', '2024-12-20'], ['Pemilihan', '2024-12-21', '2025-01-10'], ['Pelaksanaan', '2025-01-11', '2025-12-31']],
            18 => [['Perencanaan', '2024-11-01', '2024-11-30'], ['Pemilihan', '2024-12-01', '2024-12-20'], ['Pelaksanaan', '2025-01-01', '2025-12-31']],
            19 => [['Perencanaan', '2024-11-01', '2024-11-30'], ['Pemilihan', '2024-12-01', '2024-12-31'], ['Pelaksanaan', '2025-01-01', '2025-12-31']],
            20 => [['Perencanaan', '2025-03-01', '2025-03-31'], ['Pemilihan', '2025-04-01', '2025-05-15'], ['Pelaksanaan', '2025-05-16', '2025-11-15']],
            21 => [['Perencanaan', '2025-04-01', '2025-04-20'], ['Pemilihan', '2025-04-21', '2025-05-15'], ['Pelaksanaan', '2025-05-16', '2025-08-15']],
            22 => [['Perencanaan', '2025-03-01', '2025-03-15'], ['Pemilihan', '2025-03-16', '2025-04-05'], ['Pelaksanaan', '2025-04-06', '2025-05-05']],
            23 => [['Perencanaan', '2025-05-01', '2025-05-15'], ['Pemilihan', '2025-05-16', '2025-06-05'], ['Pelaksanaan', '2025-06-06', '2025-08-05']],
            24 => [['Perencanaan', '2025-06-01', '2025-06-10'], ['Pemilihan', '2025-06-11', '2025-06-25'], ['Pelaksanaan', '2025-06-26', '2025-07-25']],
            25 => [['Perencanaan', '2025-06-01', '2025-06-15'], ['Pemilihan', '2025-06-16', '2025-07-05'], ['Pelaksanaan', '2025-07-06', '2025-08-05']],
            26 => [['Perencanaan', '2025-05-01', '2025-05-15'], ['Pemilihan', '2025-05-16', '2025-06-05'], ['Pelaksanaan', '2025-06-06', '2025-07-05']],
            27 => [['Perencanaan', '2025-07-01', '2025-07-15'], ['Pemilihan', '2025-07-16', '2025-08-01'], ['Pelaksanaan', '2025-08-02', '2025-09-01']],
            28 => [['Perencanaan', '2025-07-01', '2025-07-15'], ['Pemilihan', '2025-07-16', '2025-08-01'], ['Pelaksanaan', '2025-08-02', '2025-08-20']],
            29 => [['Perencanaan', '2025-08-01', '2025-08-15'], ['Pemilihan', '2025-08-16', '2025-09-05'], ['Pelaksanaan', '2025-09-06', '2025-12-05']],
            30 => [['Perencanaan', '2026-01-01', '2026-02-15'], ['Pemilihan', '2026-02-16', '2026-04-15'], ['Pelaksanaan', '2026-04-16', '2026-10-15']],
            31 => [['Perencanaan', '2026-01-01', '2026-02-01'], ['Pemilihan', '2026-02-02', '2026-03-15'], ['Pelaksanaan', '2026-03-16', '2026-07-15']],
            32 => [['Perencanaan', '2026-01-01', '2026-02-28'], ['Pemilihan', '2026-03-01', '2026-04-30'], ['Pelaksanaan', '2026-05-01', '2026-11-30']],
            33 => [['Perencanaan', '2026-02-01', '2026-02-20'], ['Pemilihan', '2026-02-21', '2026-03-20'], ['Pelaksanaan', '2026-03-21', '2026-05-20']],
            34 => [['Perencanaan', '2026-01-01', '2026-03-15'], ['Pemilihan', '2026-03-16', '2026-05-15'], ['Pelaksanaan', '2026-05-16', '2026-12-15']],
            35 => [['Perencanaan', '2026-03-01', '2026-03-20'], ['Pemilihan', '2026-03-21', '2026-04-20'], ['Pelaksanaan', '2026-04-21', '2026-06-20']],
            36 => [['Perencanaan', '2026-04-01', '2026-04-15'], ['Pemilihan', '2026-04-16', '2026-05-05'], ['Pelaksanaan', '2026-05-06', '2026-06-05']],
            37 => [['Perencanaan', '2026-05-01', '2026-05-20'], ['Pemilihan', '2026-05-21', '2026-06-15'], ['Pelaksanaan', '2026-06-16', '2026-09-15']],
            38 => [['Perencanaan', '2026-06-01', '2026-06-15'], ['Pemilihan', '2026-06-16', '2026-07-05'], ['Pelaksanaan', '2026-07-06', '2026-10-05']],
            39 => [['Perencanaan', '2026-06-01', '2026-06-20'], ['Pemilihan', '2026-06-21', '2026-07-15'], ['Pelaksanaan', '2026-07-16', '2026-09-15']],
            40 => [['Perencanaan', '2026-05-01', '2026-05-20'], ['Pemilihan', '2026-05-21', '2026-06-15'], ['Pelaksanaan', '2026-06-16', '2026-07-15']],
            41 => [['Perencanaan', '2026-06-01', '2026-06-20'], ['Pemilihan', '2026-06-21', '2026-07-20'], ['Pelaksanaan', '2026-07-21', '2026-09-20']],
            42 => [['Perencanaan', '2026-07-01', '2026-07-15'], ['Pemilihan', '2026-07-16', '2026-08-05'], ['Pelaksanaan', '2026-08-06', '2026-09-05']],
            43 => [['Perencanaan', '2026-08-01', '2026-08-15'], ['Pemilihan', '2026-08-16', '2026-09-05'], ['Pelaksanaan', '2026-09-06', '2026-12-31']],
            44 => [['Perencanaan', '2026-08-01', '2026-08-15'], ['Pemilihan', '2026-08-16', '2026-09-05'], ['Pelaksanaan', '2026-09-06', '2026-12-31']],
            45 => [['Perencanaan', '2025-12-01', '2025-12-20'], ['Pemilihan', '2025-12-21', '2026-01-10'], ['Pelaksanaan', '2026-01-11', '2026-06-30']],
            46 => [['Perencanaan', '2026-06-01', '2026-06-15'], ['Pemilihan', '2026-06-16', '2026-07-05'], ['Pelaksanaan', '2026-07-06', '2026-12-31']],
            47 => [['Perencanaan', '2026-08-01', '2026-08-20'], ['Pemilihan', '2026-08-21', '2026-09-20'], ['Pelaksanaan', '2026-09-21', '2026-12-20']],
            48 => [['Perencanaan', '2026-06-01', '2026-06-20'], ['Pemilihan', '2026-06-21', '2026-07-20'], ['Pelaksanaan', '2026-07-21', '2026-09-20']],
            49 => [['Perencanaan', '2026-08-01', '2026-08-15'], ['Pemilihan', '2026-08-16', '2026-09-05'], ['Pelaksanaan', '2026-09-06', '2026-10-05']],
            50 => [['Perencanaan', '2025-12-01', '2025-12-31'], ['Pemilihan', '2026-01-01', '2026-01-15'], ['Pelaksanaan', '2026-01-16', '2026-12-31']],
            51 => [['Perencanaan', '2026-09-01', '2026-09-15'], ['Pemilihan', '2026-09-16', '2026-10-05'], ['Pelaksanaan', '2026-10-06', '2026-11-05']],
            52 => [['Perencanaan', '2026-07-01', '2026-07-20'], ['Pemilihan', '2026-07-21', '2026-08-15'], ['Pelaksanaan', '2026-08-16', '2026-10-15']],
        ];

        foreach ($jadwalTemplates as $pktIdx => $stages) {
            $pktId = $pktIds[$pktIdx];
            foreach ($stages as $stage) {
                DB::table('paket_jadwals')->insert([
                    'paket_pengadaan_id' => $pktId,
                    'tahapan' => $stage[0],
                    'tanggal_mulai' => $stage[1],
                    'tanggal_selesai' => $stage[2],
                    'keterangan' => null,
                    'created_at' => $now,
                    'updated_at' => $now,
                ]);
            }
        }

        // ─── PAKET LOKASI ──────────────────────────────────────────────────
        $lokasiTemplates = [
            0 => ['DKI Jakarta', 'Jakarta Pusat', 'Gambir', 'Gambir', 'Jl. Merdeka No. 1'],
            1 => ['DKI Jakarta', 'Jakarta Pusat', 'Gambir', 'Gambir', 'Jl. Merdeka No. 2'],
            2 => ['DKI Jakarta', 'Jakarta Pusat', 'Gambir', 'Gambir', 'Jl. Merdeka No. 1'],
            3 => ['DKI Jakarta', 'Jakarta Pusat', 'Gambir', 'Gambir', 'Jl. Merdeka No. 2'],
            4 => ['DKI Jakarta', 'Jakarta Pusat', 'Gambir', 'Gambir', 'Jl. Merdeka No. 4'],
            5 => ['DKI Jakarta', 'Jakarta Pusat', 'Gambir', 'Gambir', 'Jl. Merdeka No. 8'],
            6 => ['DKI Jakarta', 'Jakarta Pusat', 'Gambir', 'Gambir', 'Jl. Merdeka No. 5'],
            7 => ['DKI Jakarta', 'Jakarta Pusat', 'Gambir', 'Gambir', 'Jl. Merdeka No. 5'],
            8 => ['DKI Jakarta', 'Jakarta Pusat', 'Gambir', 'Gambir', 'Jl. Merdeka No. 5'],
            9 => ['DKI Jakarta', 'Jakarta Pusat', 'Gambir', 'Gambir', 'Jl. Merdeka No. 6'],
            10 => ['DKI Jakarta', 'Jakarta Pusat', 'Gambir', 'Gambir', 'Jl. Merdeka No. 6'],
            11 => ['DKI Jakarta', 'Jakarta Pusat', 'Gambir', 'Gambir', 'Jl. Merdeka No. 1'],
            12 => ['DKI Jakarta', 'Jakarta Pusat', 'Gambir', 'Gambir', 'Jl. Merdeka No. 3'],
            13 => ['DKI Jakarta', 'Jakarta Pusat', 'Gambir', 'Gambir', 'Jl. Merdeka No. 9'],
            14 => ['DKI Jakarta', 'Jakarta Pusat', 'Gambir', 'Gambir', 'Jl. Merdeka No. 4'],
            15 => ['DKI Jakarta', 'Jakarta Pusat', 'Gambir', 'Gambir', 'Jl. Merdeka No. 4'],
            16 => ['DKI Jakarta', 'Jakarta Pusat', 'Gambir', 'Gambir', 'Jl. Merdeka No. 8'],
            17 => ['DKI Jakarta', 'Jakarta Pusat', 'Gambir', 'Gambir', 'Jl. Merdeka No. 10'],
            18 => ['DKI Jakarta', 'Jakarta Pusat', 'Gambir', 'Gambir', 'Jl. Merdeka No. 10'],
            19 => ['DKI Jakarta', 'Jakarta Pusat', 'Gambir', 'Gambir', 'Jl. Merdeka No. 10'],
            20 => ['DKI Jakarta', 'Jakarta Pusat', 'Gambir', 'Gambir', 'Jl. Merdeka No. 7'],
            21 => ['DKI Jakarta', 'Jakarta Timur', 'Pulo Gadung', 'Kayu Putih', 'Jl. Akses Kantor'],
            22 => ['DKI Jakarta', 'Jakarta Pusat', 'Gambir', 'Gambir', 'Jl. Merdeka No. 1'],
            23 => ['DKI Jakarta', 'Jakarta Pusat', 'Gambir', 'Gambir', 'Jl. Merdeka No. 7'],
            24 => ['DKI Jakarta', 'Jakarta Pusat', 'Gambir', 'Gambir', 'Jl. Merdeka No. 6'],
            25 => ['DKI Jakarta', 'Jakarta Pusat', 'Gambir', 'Gambir', 'Jl. Merdeka No. 9'],
            26 => ['DKI Jakarta', 'Jakarta Pusat', 'Gambir', 'Gambir', 'Jl. Merdeka No. 4'],
            27 => ['DKI Jakarta', 'Jakarta Pusat', 'Gambir', 'Gambir', 'Jl. Merdeka No. 9'],
            28 => ['DKI Jakarta', 'Jakarta Pusat', 'Gambir', 'Gambir', 'Jl. Merdeka No. 9'],
            29 => ['DKI Jakarta', 'Jakarta Pusat', 'Gambir', 'Gambir', 'Jl. Merdeka No. 6'],
            // 2026
            30 => ['DKI Jakarta', 'Jakarta Pusat', 'Gambir', 'Gambir', 'Jl. Merdeka No. 8'],
            31 => ['DKI Jakarta', 'Jakarta Pusat', 'Gambir', 'Gambir', 'Jl. Merdeka No. 8'],
            32 => ['DKI Jakarta', 'Jakarta Pusat', 'Gambir', 'Gambir', 'Jl. Merdeka No. 5'],
            33 => ['DKI Jakarta', 'Jakarta Pusat', 'Gambir', 'Gambir', 'Jl. Merdeka No. 5'],
            34 => ['DKI Jakarta', 'Jakarta Pusat', 'Gambir', 'Gambir', 'Jl. Merdeka No. 7'],
            35 => ['DKI Jakarta', 'Jakarta Pusat', 'Gambir', 'Gambir', 'Jl. Merdeka No. 5'],
            36 => ['DKI Jakarta', 'Jakarta Pusat', 'Gambir', 'Gambir', 'Jl. Merdeka No. 8'],
            37 => ['DKI Jakarta', 'Jakarta Pusat', 'Gambir', 'Gambir', 'Jl. Merdeka No. 9'],
            38 => ['DKI Jakarta', 'Jakarta Pusat', 'Gambir', 'Gambir', 'Jl. Merdeka No. 4'],
            39 => ['DKI Jakarta', 'Jakarta Pusat', 'Gambir', 'Gambir', 'Jl. Merdeka No. 9'],
            40 => ['DKI Jakarta', 'Jakarta Pusat', 'Gambir', 'Gambir', 'Jl. Merdeka No. 1'],
            41 => ['DKI Jakarta', 'Jakarta Pusat', 'Gambir', 'Gambir', 'Jl. Merdeka No. 7'],
            42 => ['DKI Jakarta', 'Jakarta Pusat', 'Gambir', 'Gambir', 'Jl. Merdeka No. 2'],
            43 => ['DKI Jakarta', 'Jakarta Pusat', 'Gambir', 'Gambir', 'Jl. Merdeka No. 10'],
            44 => ['DKI Jakarta', 'Jakarta Pusat', 'Gambir', 'Gambir', 'Jl. Merdeka No. 10'],
            45 => ['DKI Jakarta', 'Jakarta Pusat', 'Gambir', 'Gambir', 'Jl. Merdeka No. 10'],
            46 => ['DKI Jakarta', 'Jakarta Pusat', 'Gambir', 'Gambir', 'Jl. Merdeka No. 10'],
            47 => ['DKI Jakarta', 'Jakarta Pusat', 'Gambir', 'Gambir', 'Jl. Merdeka No. 7'],
            48 => ['DKI Jakarta', 'Jakarta Pusat', 'Gambir', 'Gambir', 'Jl. Merdeka No. 5'],
            49 => ['DKI Jakarta', 'Jakarta Pusat', 'Gambir', 'Gambir', 'Jl. Merdeka No. 5'],
            50 => ['DKI Jakarta', 'Jakarta Pusat', 'Gambir', 'Gambir', 'Jl. Merdeka No. 5'],
            51 => ['DKI Jakarta', 'Jakarta Pusat', 'Gambir', 'Gambir', 'Jl. Merdeka No. 6'],
            52 => ['DKI Jakarta', 'Jakarta Pusat', 'Gambir', 'Gambir', 'Jl. Merdeka No. 5'],
        ];

        foreach ($lokasiTemplates as $pktIdx => $lok) {
            DB::table('paket_lokasis')->insert([
                'paket_pengadaan_id' => $pktIds[$pktIdx],
                'provinsi' => $lok[0],
                'kabupaten_kota' => $lok[1],
                'kecamatan' => $lok[2],
                'kelurahan_desa' => $lok[3],
                'detail_alamat' => $lok[4],
                'created_at' => $now,
                'updated_at' => $now,
            ]);
        }

        // ─── RIWAYAT PERSETUJUAN ───────────────────────────────────────────
        $riwayatTemplates = [
            // dipublikasikan: full workflow
            // [paketIdx, aksi, user_id, status_dari, status_ke, catatan]
            0 => [ // PKT.2024.001 - dipublikasikan
                ['submit', 3, 'draft', 'diajukan', 'Pengajuan paket pengadaan laptop ASN'],
                ['verifikasi_setuju', 13, 'diajukan', 'diverifikasi', 'Verifikasi anggaran disetujui, dokumen lengkap'],
                ['approve_setuju', 15, 'diverifikasi', 'disetujui', 'Disetujui untuk dilanjutkan ke proses pengadaan'],
                ['publikasi', 3, 'disetujui', 'dipublikasikan', 'Paket berhasil dipublikasikan untuk proses tender'],
            ],
            1 => [ // PKT.2024.002
                ['submit', 4, 'draft', 'diajukan', ''],
                ['verifikasi_setuju', 13, 'diajukan', 'diverifikasi', 'Verifikasi disetujui'],
                ['approve_setuju', 15, 'diverifikasi', 'disetujui', 'Disetujui'],
                ['publikasi', 4, 'disetujui', 'dipublikasikan', ''],
            ],
            2 => [ // PKT.2024.003 - disetujui (no publikasi)
                ['submit', 3, 'draft', 'diajukan', ''],
                ['verifikasi_setuju', 13, 'diajukan', 'diverifikasi', ''],
                ['approve_setuju', 15, 'diverifikasi', 'disetujui', 'Disetujui'],
            ],
            3 => [ // PKT.2024.004
                ['submit', 4, 'draft', 'diajukan', ''],
                ['verifikasi_setuju', 14, 'diajukan', 'diverifikasi', ''],
                ['approve_setuju', 15, 'diverifikasi', 'disetujui', 'Disetujui'],
                ['publikasi', 4, 'disetujui', 'dipublikasikan', ''],
            ],
            4 => [ // PKT.2024.005
                ['submit', 6, 'draft', 'diajukan', ''],
                ['verifikasi_setuju', 13, 'diajukan', 'diverifikasi', ''],
                ['approve_setuju', 15, 'diverifikasi', 'disetujui', ''],
                ['publikasi', 6, 'disetujui', 'dipublikasikan', ''],
            ],
            5 => [ // PKT.2024.006 - disetujui
                ['submit', 10, 'draft', 'diajukan', 'Pengajuan aplikasi layanan publik'],
                ['verifikasi_setuju', 14, 'diajukan', 'diverifikasi', 'Dokumen teknis sudah lengkap'],
                ['approve_setuju', 15, 'diverifikasi', 'disetujui', 'Disetujui oleh pimpinan'],
            ],
            6 => [ // PKT.2024.007
                ['submit', 7, 'draft', 'diajukan', ''],
                ['verifikasi_setuju', 13, 'diajukan', 'diverifikasi', ''],
                ['approve_setuju', 15, 'diverifikasi', 'disetujui', ''],
                ['publikasi', 7, 'disetujui', 'dipublikasikan', ''],
            ],
            7 => [ // PKT.2024.008
                ['submit', 7, 'draft', 'diajukan', ''],
                ['verifikasi_setuju', 13, 'diajukan', 'diverifikasi', ''],
                ['approve_setuju', 15, 'diverifikasi', 'disetujui', ''],
                ['publikasi', 7, 'disetujui', 'dipublikasikan', ''],
            ],
            8 => [ // PKT.2024.009
                ['submit', 7, 'draft', 'diajukan', ''],
                ['verifikasi_setuju', 13, 'diajukan', 'diverifikasi', ''],
                ['approve_setuju', 15, 'diverifikasi', 'disetujui', ''],
                ['publikasi', 7, 'disetujui', 'dipublikasikan', ''],
            ],
            9 => [ // PKT.2024.010 - disetujui
                ['submit', 8, 'draft', 'diajukan', ''],
                ['verifikasi_setuju', 13, 'diajukan', 'diverifikasi', ''],
                ['approve_setuju', 15, 'diverifikasi', 'disetujui', ''],
            ],
            10 => [ // PKT.2024.011
                ['submit', 8, 'draft', 'diajukan', ''],
                ['verifikasi_setuju', 13, 'diajukan', 'diverifikasi', ''],
                ['approve_setuju', 15, 'diverifikasi', 'disetujui', ''],
                ['publikasi', 8, 'disetujui', 'dipublikasikan', ''],
            ],
            11 => [ // PKT.2024.012
                ['submit', 3, 'draft', 'diajukan', ''],
                ['verifikasi_setuju', 14, 'diajukan', 'diverifikasi', ''],
                ['approve_setuju', 15, 'diverifikasi', 'disetujui', ''],
                ['publikasi', 3, 'disetujui', 'dipublikasikan', ''],
            ],
            12 => [ // PKT.2024.013 - disetujui
                ['submit', 5, 'draft', 'diajukan', ''],
                ['verifikasi_setuju', 13, 'diajukan', 'diverifikasi', ''],
                ['approve_setuju', 15, 'diverifikasi', 'disetujui', ''],
            ],
            13 => [ // PKT.2024.014
                ['submit', 11, 'draft', 'diajukan', ''],
                ['verifikasi_setuju', 13, 'diajukan', 'diverifikasi', ''],
                ['approve_setuju', 15, 'diverifikasi', 'disetujui', ''],
                ['publikasi', 11, 'disetujui', 'dipublikasikan', ''],
            ],
            // 2025
            14 => [ // PKT.2025.001
                ['submit', 6, 'draft', 'diajukan', ''],
                ['verifikasi_setuju', 13, 'diajukan', 'diverifikasi', ''],
                ['approve_setuju', 15, 'diverifikasi', 'disetujui', ''],
                ['publikasi', 6, 'disetujui', 'dipublikasikan', ''],
            ],
            15 => [ // PKT.2025.002 - disetujui
                ['submit', 6, 'draft', 'diajukan', ''],
                ['verifikasi_setuju', 13, 'diajukan', 'diverifikasi', 'Anggaran sesuai DPA'],
                ['approve_setuju', 15, 'diverifikasi', 'disetujui', ''],
            ],
            16 => [ // PKT.2025.003 - diverifikasi
                ['submit', 10, 'draft', 'diajukan', 'Sosialisasi pelayanan publik'],
                ['verifikasi_setuju', 13, 'diajukan', 'diverifikasi', 'Disetujui verifikator'],
            ],
            17 => [ // PKT.2025.004
                ['submit', 12, 'draft', 'diajukan', ''],
                ['verifikasi_setuju', 13, 'diajukan', 'diverifikasi', ''],
                ['approve_setuju', 15, 'diverifikasi', 'disetujui', ''],
                ['publikasi', 12, 'disetujui', 'dipublikasikan', ''],
            ],
            18 => [ // PKT.2025.005
                ['submit', 12, 'draft', 'diajukan', ''],
                ['verifikasi_setuju', 13, 'diajukan', 'diverifikasi', ''],
                ['approve_setuju', 15, 'diverifikasi', 'disetujui', ''],
                ['publikasi', 12, 'disetujui', 'dipublikasikan', ''],
            ],
            19 => [ // PKT.2025.006 - diverifikasi
                ['submit', 12, 'draft', 'diajukan', 'Jasa keamanan 2025'],
                ['verifikasi_setuju', 14, 'diajukan', 'diverifikasi', 'Disetujui verifikator'],
            ],
            20 => [ // PKT.2025.007 - disetujui
                ['submit', 9, 'draft', 'diajukan', ''],
                ['verifikasi_setuju', 13, 'diajukan', 'diverifikasi', 'Rehab gedung anggaran besar perlu review'],
                ['approve_setuju', 15, 'diverifikasi', 'disetujui', 'Disetujui pimpinan'],
            ],
            21 => [ // PKT.2025.008
                ['submit', 9, 'draft', 'diajukan', ''],
                ['verifikasi_setuju', 13, 'diajukan', 'diverifikasi', ''],
                ['approve_setuju', 15, 'diverifikasi', 'disetujui', ''],
                ['publikasi', 9, 'disetujui', 'dipublikasikan', ''],
            ],
            22 => [ // PKT.2025.009
                ['submit', 3, 'draft', 'diajukan', ''],
                ['verifikasi_setuju', 13, 'diajukan', 'diverifikasi', ''],
                ['approve_setuju', 15, 'diverifikasi', 'disetujui', ''],
                ['publikasi', 3, 'disetujui', 'dipublikasikan', ''],
            ],
            23 => [ // PKT.2025.010 - diverifikasi
                ['submit', 9, 'draft', 'diajukan', 'Konsultan pengawasan rehab'],
                ['verifikasi_setuju', 13, 'diajukan', 'diverifikasi', 'Disetujui, menunggu approve pimpinan'],
            ],
            25 => [ // PKT.2025.012 - diajukan
                ['submit', 11, 'draft', 'diajukan', 'Percetakan dokumen tahunan'],
            ],
            26 => [ // PKT.2025.013 - dikembalikan
                ['submit', 6, 'draft', 'diajukan', 'Pengadaan seragam dinas'],
                ['verifikasi_kembali', 13, 'diajukan', 'dikembalikan', 'Dokumen spesifikasi teknis tidak lengkap, harap lengkapi KAK dan RAB detail'],
            ],
            27 => [ // PKT.2025.014 - diverifikasi
                ['submit', 11, 'draft', 'diajukan', ''],
                ['verifikasi_setuju', 14, 'diajukan', 'diverifikasi', 'Disetujui'],
            ],
            28 => [ // PKT.2025.015
                ['submit', 11, 'draft', 'diajukan', ''],
                ['verifikasi_setuju', 13, 'diajukan', 'diverifikasi', ''],
                ['approve_setuju', 15, 'diverifikasi', 'disetujui', ''],
                ['publikasi', 11, 'disetujui', 'dipublikasikan', ''],
            ],
            29 => [ // PKT.2025.016 - disetujui
                ['submit', 8, 'draft', 'diajukan', ''],
                ['verifikasi_setuju', 13, 'diajukan', 'diverifikasi', ''],
                ['approve_setuju', 15, 'diverifikasi', 'disetujui', ''],
            ],
            // 2026
            34 => [ // PKT.2026.005 - diajukan
                ['submit', 9, 'draft', 'diajukan', 'Pembangunan gedung serbaguna 3 lantai diajukan'],
            ],
            40 => [ // PKT.2026.011 - diajukan
                ['submit', 3, 'draft', 'diajukan', 'Pengadaan kendaraan dinas baru'],
            ],
            48 => [ // PKT.2026.019 - diajukan
                ['submit', 7, 'draft', 'diajukan', 'Pengadaan peralatan lab komputer'],
            ],
        ];

        foreach ($riwayatTemplates as $pktIdx => $aksiList) {
            $pktId = $pktIds[$pktIdx];
            $urutan = 1;
            foreach ($aksiList as $aksi) {
                DB::table('riwayat_persetujuans')->insert([
                    'paket_pengadaan_id' => $pktId,
                    'user_id' => $aksi[1],
                    'aksi' => $aksi[0],
                    'status_dari' => $aksi[2],
                    'status_ke' => $aksi[3],
                    'catatan' => $aksi[4] ?: null,
                    'created_at' => $now,
                    'updated_at' => $now,
                ]);
                $urutan++;
            }
        }
    }
}
